name: Publish

on:
  pull_request_target:
    types: [closed]
    branches:
      - development
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Checkout all branches and tags
      - name: "Use NodeJS 18"
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Build and test
      - run: npm -v
      - run: npm install --no-package-lock
      - run: npm run build
      - run: npm test

      - name: "Git Config"
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          git config advice.addIgnoredFile false

      - name: "Lerna Version & Publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm set //registry.npmjs.org/:_authToken=${{ secrets.NPMJS_TOKEN }}
          npm whoami
          npx lerna version --conventional-commits --yes
          npx lerna publish from-git --yes --no-verify-access
